### ISSUE TITLE
bad name

### ISSUE THREAD

**Issue by RomBecker** [stavgn/StalkerPlus#2]
https://github.com/stavgn/StalkerPlus/blob/2e425e5825ba84a0fa9b958ac473279eae8e20e9/app/components/generalInfo.js#L3

GENERALINFO = BAD NAME
i can't understand what it does by the name???
I dont want to solve a puzzle when doing you a cr....
if its a react component give it an "componentish" name it's important.
example: MainAppContainer \ InformartionPanel ETC...

**Comment by stavgn** [comment]
no more generalInfo component.  wasn't necessary
